### ISSUE TITLE
Ex/ssd

### ISSUE THREAD

**Issue by zorgsky** [mrdear/Ryzen-5800x-X570-AORUS-PRO-WIFI-OC0.7.X#1]
You may try add nvme device path to DeviceProperties and use built-in <Data> 01000000.
Hope it will help you out.
Cheers.

**Comment by mrdear** [comment]
Thank you, recently too busy, I will try in the Spring Festival period

**Comment by mrdear** [comment]
Thanks, this problem has been solved, the tutorial can refer to the following link.

[https://www.reddit.com/r/hackintosh/comments/f0cc4t/internal_drives_shown_as_external_opencore_amd/](https://www.reddit.com/r/hackintosh/comments/f0cc4t/internal_drives_shown_as_external_opencore_amd/)
